- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/MobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverPool.java
Added touch action swipe example for checking on different apps and
platforms.
> Minor fix in DriverPool.

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/MobileUtils.java
Checked 5.0.1, 6.0.1 and 7.0 android
> Fix for swipe with TouchActions

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/jira/Jira.java
> ISSUE-171: fixed exception in case of incorrect Jira ticket format.

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidUtils.java
1. Added timeout with default 5min to scroll mechanism. It will throw an exception if scroll wouldn't return desired element within 5 min.
> Adding timeout to scroll mechanism

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/annotations/ClassChain.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
- implemented locator strategy By.classChain from Appium ios
> ClassChain Feature: implemented locator strategy By.classChain from Appium ios

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- implemented feature to perform 'format' for class chain locators in webelement @FindBy
> support 'format' feature for ClassChain locators

- carina-api/pom.xml
- carina-aws-s3/pom.xml
- carina-commons/pom.xml
- carina-core/pom.xml
- carina-dataprovider/pom.xml
- carina-grid/pom.xml
- carina-hockeyapp/pom.xml
- carina-utils/pom.xml
- carina-webdriver/pom.xml
- pom.xml
> ISSUE-263: Pom files clean up

- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/testrail/dto/Runs.java
> HotFix: Added support for the old addRun method

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Messager.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/MobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/AbstractUIObject.java
> handled use-cases with AbstractUiObjects and searchContext usage

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/I18N.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/L10N.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/Resources.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/MobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
don't merge please. Still under testing...
> DON'T MERGE: improvements into the loggers for UI exceptions

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
1) log extractor;
2) add uploading of XML tree to artifacts.
> Add new functionality:

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> isElementWithTextPresent() logic was fixed for usage with web elements inside AbstractUIObject

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidService.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/ios/IosUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/MobileUtils.java
Old methods present but Deprecated
> Moved hideKeyboard to MobileUtils.

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/MobileUtils.java
1. Added an overloaded swipeInContainer() that returns original swipeInContainer() that has new param added for handling of custom swipe count
> Adding handling for swipe count in MobileUtils.swipeInContainer()

- carina-hockeyapp/src/main/java/com/qaprosoft/hockeyapp/HockeyAppManager.java
Main point of this PR is to add a 3rd way to pull items from HockeyApp.
1. latest
2. version info (i.e. 10.0.0)
3. version info + build (i.e. 10.0.0.624)
> Adding in the ability to pull down builds by shortversion + build instead of just latest and/or shortversion

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
> QAT-2909: Driver restart logic was updated

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- pom.xml
> add new screenshot uploading logic

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/ChromeCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/EdgeCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/FirefoxCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/IECapabilities.java
- docs/configuration.md
https://github.com/qaprosoft/carina/issues/499
> added possibility to start Chrome and Firefox using localized language

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Messager.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
Window size for chrome was configured hardcoded - switched to maximized size
fixed minor typos and summary comments
> Chrome window size is now maximized after creation

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> 576: - doType method was fixed (strings are not shown decrypt in logs for input fields)

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/PlaceholderResolver.java
> 629: message 'Value not resolved by key..' not show for EnvArg url now

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
> do not restart proxy during driver restart on the same device

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/MobileUtils.java
> build-snapshot: Added zoom action to MobileUtils

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/MobileUtils.java
> issue_622: small improvements for zooming - changed start/end delta beetwen points

- carina-grid/src/main/java/com/qaprosoft/carina/grid/MobileRemoteProxy.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringAppiumCommandExecutor.java
Add extra device info when driver creation failed
> build-snapshot: Add extra device info when driver creation failed 

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> build-snapshot: changed Locatable class import package location

- carina-hockeyapp/src/main/java/com/qaprosoft/hockeyapp/HockeyAppManager.java
Main change here is switching the LOGGER.info over to LOGGER.debug to reduce the noise that HockeyAppManager causes when it's scanning for a build to download.
> build-snapshot: Reducing Noise on HockeyAppManager download

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedFieldDecorator.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedFindBy.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedFindByBuilder.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/LocalizedAnnotations.java
Was introduced new annotation to find elements - ExtendedFindBy. Also was added find by image functionality.
> build-snapshot: Added ExtendedFindBy annotation. Added find by image functionality.

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/ftp/FtpUtils.java
> build-snapshot: Changed ftp mode to local passive mode

- carina-commons/src/main/java/com/qaprosoft/carina/commons/models/RemoteDevice.java
> build-snapshot: Added handling of null for device name and UDID.

- carina-aws-s3/src/main/java/com/qaprosoft/amazon/client/AmazonS3Client.java
> build-snapshot: pre upload task was executed in main thread

- carina-aws-s3/src/main/java/com/qaprosoft/amazon/client/AmazonS3Client.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/report/ZafiraConfigurator.java
- carina-reporting/pom.xml
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/Artifacts.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/AsyncArtifact.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- pom.xml
Updating zafira-client to 3.3.73-SNAPSHOT
Async artifacts uploading was added
> build-snapshot: async artifacts uploading

- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/Artifacts.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/AsyncArtifact.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
> build-snapshot: logic of thumbnails collecting was changed

- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
- carina-proxy/src/test/java/com/qaprosoft/carina/browsermobproxy/BrowserMobTest.java
- carina-utils/pom.xml
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
This pull request will allow for the use of multiple BrowserMob Proxies across multiple threads.
> build-snapshot: Browsermob Proxy multi-threading implementation

- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/http/HttpClient.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/http/HttpMethodType.java
- carina-api/src/test/java/com/qaprosoft/carina/core/foundation/httpclient/HttpMethodTypeTest.java
> Adding OPTIONS http method. build-snapshot

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
add method to do drag and drop on html5
> add method to do drag and drop on html5

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/FirefoxCapabilities.java
put FirefoxOptions instead of DesiredCapabilities.firefox();
> add FirefoxOptions

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
> build-snapshot: comment fixed

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/async/AsyncOperation.java
> build-snapshot: async operation entity was moved to synhronized test suite layer

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/DriverFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/MoonRecordingListener.java
- pom.xml
> Moon recording

- pom.xml
> use maven -surefire 3.0.0-M3

- pom.xml
> build-snapshot: zafira client reverted to 3.3.92-SNAPSHOT

- carina-grid/src/main/java/com/qaprosoft/carina/grid/MobileCapabilityMatcher.java
> add support for mobile web execution via QPS-HUB

- archetype/src/main/resources/archetype-resources/src/test/resources/api/users/_post/rs.json
Update the response from the post method.
> update response from create user endpoint.

- carina-grid/src/main/java/com/qaprosoft/carina/grid/MobileCapabilityMatcher.java
> added support for mobile web testing in QPS cloud

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/tag/TagManager.java
- pom.xml
> add possibility to declare custom tags via code

- pom.xml
> bump up zafira-client to add static tags registration onTestStart

- pom.xml
Fixed maven compiler plugin configuration
> build-snapshot: Updated maven compiler plugin configuration

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/mobile/MobileCapabilies.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
>  add fullResetCapability

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/ios/IIosUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/ios/IosUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
migrated AndroidUtils and IosUtils to IAndroidUtils and IIosUtils
> migrated AndroidUtils and IosUtils to IAndroidUtils and IIosUtils

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/report/ZafiraConfigurator.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/tag/TagManager.java
> build-snapshot: bug connected with tags overriding was fixed

- archetype/src/main/resources/archetype-resources/src/main/resources/_config.properties
- carina-aws-s3/src/main/java/com/qaprosoft/amazon/client/AmazonS3Client.java
- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
- docs/configuration.md
> build-snapshot: Added logic to upload UI dump report to s3

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidService.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
> added isAppRunning()

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
> build-snapshot: mobile vnc support for moon

- archetype/src/main/resources/archetype-resources/pom.xml
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/performance/Timer.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/ownership/Ownership.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/DriverFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/ZebrunnerRecordingListener.java
set of fixes for method ownership
> New method owner

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- Edge and IE capabilities refactored
> build-snapshot: browser resize added

- carina-grid/Dockerfile
- carina-grid/generate_config
- carina-grid/pom.xml
> Grid 3.141.59

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
> build-snapshot: workaround hanged test during screenshot and ui dump generation

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
> hide "Method has not yet been implemented" error to debug layer

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/report/ZafiraConfigurator.java
- carina-core/src/test/java/com/qaprosoft/carina/core/foundation/zafira/ZafiraClientTest.java
- carina-grid/src/main/java/com/qaprosoft/carina/grid/integration/STF.java
- carina-utils/src/main/resources/log4j.properties
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- pom.xml
> build-snapshot: client refactoring 

- carina-dataprovider/pom.xml
- pom.xml
> build-snapshot: google api sheets dependency was added

- carina-grid/pom.xml
- pom.xml
> grid build fix

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/ftp/FtpUtils.java
> handled any runtime exception and error for FtpUtils disconnect

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/naming/TestNamingUtil.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringAppiumCommandExecutor.java
> return original exception with stacktrace for driver startup failure

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
- carina-utils/src/test/java/com/qaprosoft/carina/core/utils/RTest.java
- carina-utils/src/test/resources/_config.properties
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/CapabilitiesLoader.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/CapabilitiesLoaderTest.java
> ability to override configuration and capabilities for current test/thread only

- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethod.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodV2.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
- carina-utils/src/main/resources/carina-log4j.properties
- carina-utils/src/main/resources/log4j.properties
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> making Xpath case insensitive

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
Add a boolean method to IMobileUtil for checking whether keyboard is shown on iOS and Android.
> build-snapshot: Add isKeyboardShown method to IMobileUtils

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/ChromeCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/FirefoxCapabilities.java
> Added support for chrome arguments and experimental options manipulation

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/mobile/devices/android/phone/pages/fakegps/FakeGpsPage.java
- pom.xml
> bump up to latest appium java client 7.2.0

- carina-dataprovider/src/main/java/com/qaprosoft/carina/core/foundation/dataprovider/core/DataProviderFactory.java
- carina-dataprovider/src/main/java/com/qaprosoft/carina/core/foundation/dataprovider/core/impl/BaseDataProvider.java
> build-snapshot: bug connected with dataprovider rerun skipped tests was fixed

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- pom.xml
> default options and capabilities for mobile chrome

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringAppiumCommandExecutor.java
- pom.xml
> EventFiringAppiumCommandExecutor syncup with 7.2.0 appium java code

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/FileManager.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
> NPE fix for invalid report folder generation

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/naming/TestNamingUtil.java
> bug connected with test name in parallel execution are differents was (NO MERGE!!!!)

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> fixed pattern for caseinsensitive xpath till the closing quote of value

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> fixed attributePattern for using with double quotes

- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
- carina-proxy/src/test/java/com/qaprosoft/carina/browsermobproxy/BrowserMobPortsRangeTest.java
> Fix for unit tests in carina proxy module

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> adjusted replacement depending on value with double or single quotes

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/AbstractTest.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/factory/DeviceType.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/appletv/IRemoteControllerAppleTV.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/appletv/RemoteControlKeyword.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/tvos/AppleTVTest.java
> Adding tvOS platform

- pom.xml
build-snapshot: stf integration removed
> - zafira-client changed to 4.0.40-SNAPSHOT

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/report/ZafiraConfigurator.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/jira/Jira.java
- carina-utils/src/test/java/com/qaprosoft/carina/core/foundation/jira/JiraTest.java
- pom.xml
> build-snapshot: possibility to add known issue runtime was added

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
> be able to generate presign url for aws s3 artifacts

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DesktopRecordingListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/IDriverCommandListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/MobileRecordingListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/ZebrunnerRecordingListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/ZebrunnerSessionLogListener.java
6.3.32-SNAPSHOT should be tested, all we do is adding session logs link when video recording is enabled.
> Zebrunner Appium / Selenium session logs

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/locator/CaseInsensitiveTest.java
> Issue 865 - fixed caseinsensitive and added unit tests

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/locator/CaseInsensitiveTest.java
> build-snapshot: Issue 865 - updated pattern for caseinsensitive xpath with 'or'

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
Add implementation of format method in ExtendedWebElement class for UiAutomator selector strategy
> build-snapshot: add implementation of format method for UiAutomator selector strategy

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/naming/TestNamingUtil.java
- carina-utils/src/test/java/com/qaprosoft/carina/core/foundation/performance/PerformanceTest.java
- carina-utils/src/test/java/com/qaprosoft/carina/core/utils/RTest.java
- pom.xml
> Bump up to the latest 7.1.0 TestNG

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-utils/src/test/java/com/qaprosoft/carina/core/utils/MethodOwnerTest.java
> #930: handled class cast issue for invalid tests

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/LocalizedAnnotations.java
add L10N implementation in buildBy method of LocalizedAnnotations class for UiAutomator selector strategy
> build-snapshot: add L10N implementation for UiAutomator selector strategy

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/performance/ACTION_NAME.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/FileManager.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DesktopRecordingListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringSeleniumCommandExecutor.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/MobileRecordingListener.java
> Recordings

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DesktopRecordingListener.java
> fix for web recordings

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/ftp/FtpUtils.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/video/VideoAnalyzer.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/MobileRecordingListener.java
> reviewed and updated log levels for FtpUtils

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
> don't populate performance appium logs at the end

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/ftp/FtpUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/MobileRecordingListener.java
> catched any exception in getDriverLogs

- pom.xml
> switch to zafira-client snapshot

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
> removed runAsync as artifacts.add already implement it

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
- docs/configuration.md
> #970: added possibility to override auto_download_folder location

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/AbstractTest.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-core/src/main/resources/META-INF/services/org.testng.ITestNGListener
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/retry/RetryAnalyzer.java
> switched to the non-deprecated methods for operating with RetryAnalyzer

- archetype/src/main/resources/archetype-resources/src/main/resources/_config.properties
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
> #883: improved thread-count manipulation

- carina-core/pom.xml
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/AbstractTest.java
- carina-core/src/main/resources/META-INF/services/org.testng.ITestNGListener
- pom.xml
> build snapshot: TestNG registration ordering was added

- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethod.java
- carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodTest.java
- carina-api/src/test/resources/api.properties
> #766 added method to get request body as a String object

- carina-api/src/main/java/com/qaprosoft/apitools/builder/GenerateProcessor.java
- carina-api/src/main/java/com/qaprosoft/apitools/builder/PropertiesKeywords.java
- carina-api/src/test/java/com/qaprosoft/apitools/builder/GenerateProcessorTest.java
> #874 fixed Random string generation

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/resources/config.properties
> #997: disable new feature by default which could parse suite attribute

- carina-core/pom.xml
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/AbstractTest.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/resources/META-INF/services/org.testng.ITestNGListener
- pom.xml
> changed listeners order

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
- carina-utils/src/test/java/com/qaprosoft/carina/core/utils/RTest.java
- carina-utils/src/test/resources/__testdata.properties
Crypto usage in any property.
You can use {crypt:...} parameter in any property file (config, testdata, api, etc.)
> Crypto usage in any property

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
Hotfix to unblock actual solutions which were used for properties decryption.
> Hotfix to unblock actual solutions in crypto

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Messager.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ElementLoadingStrategy.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/AbstractPage.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/AbstractUIObject.java
Improvements for web test automation:
- implementation of #1010 ELEMENT_LOADING_STRATEGY support
- adding of loading marker for AbstractUIObject
- adding of assertPageOpened() method for AbstractPage
- adding of waitForJSToLoad() method for AbstractPage
> build-snapshot: UI automation improvements (including resolution for #1010)

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Messager.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ElementLoadingStrategy.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/AbstractPage.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/AbstractUIObject.java
> Revert "build-snapshot: UI automation improvements (including resolution for #1010)"

- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethod.java
> fix issue when header value contain equal sign

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/TestResultItem.java
> #1001: made local reports links more flexible (build-snapshot)

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
> #1026: don't produce gallery.zip during unit tests execution (build-snapshot)

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/jira/Jira.java
> #978: removed all synchronized for jira static methods (build-snapshot)

- carina-crypto/src/main/java/com/qaprosoft/carina/core/foundation/crypto/CryptoTool.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
- carina-utils/src/test/java/com/qaprosoft/carina/core/utils/RTest.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> #1033: unified encryption/decryption

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/listeners/TestNamingListener.java
> #1043: hanled inex bound array exception for special use-case

- pom.xml
> bumpup to java appium 7.3.0 client (build-snapshot)

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- docs/configuration.md
> #1060: provide capability to disable carina thread_count manipulation

- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
> #1067: added logger error in case of any problem

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
> #1070: take capabilities into account when setting device OS

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
> #1077: Fixed mistake with Firefox preferences

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/report/ZafiraConfigurator.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/Artifacts.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/AsyncArtifact.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- pom.xml
> Revert "build-snapshot: Migrated to new artifacts upload logic usage"

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> #1089: simplified refindElement code block

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
> catch any exception during server log reading

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/PlaceholderResolver.java
> #1052: fix for infinit loop due to the missed project_report_directory

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/DriverFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
> [#1021] hub_mode property was replaced with capabilities.provider and HubType enum was deleted

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
> #1111: added disabling of enableVNC and Video caps in case of headless mode. Added more logs.

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
> #1078: made ability to use custom retry analyzer

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> improve timeouts messages for positove and negative cases

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> 7.0-beta1: improve timeouts messages for positove and negative cases

- archetype/src/main/resources/archetype-resources/src/test/java/carina/demo/WebSampleTest.java
Fixed asserts from WebSampleTest in testCompareModels()
> fixed asserts from WebSampleTest in testCompareModels()

- archetype/src/main/resources/archetype-resources/src/main/resources/_config.properties
- carina-api/src/test/resources/config.properties
- carina-aws-s3/src/test/resources/config.properties
- carina-core/src/main/resources/config.properties
- carina-proxy/src/test/resources/config.properties
- carina-reporting/src/test/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/log/ThreadLogAppender.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/PlaceholderResolver.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
- carina-utils/src/test/resources/_config.properties
- carina-utils/src/test/resources/config.properties
- carina-webdriver/src/test/resources/config.properties
- docs/configuration.md
> #1119: return default max_log_file_size=150 in resolver

- carina-webdriver/pom.xml
> build-snapshot: Updating com.itextpdf version to 5.5.13.2 in carina-webdriver module

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
> Added fluentwait to resizeBrowserWindow method in DesktopFactory class

- archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetype/src/main/resources/archetype-resources/pom.xml
- archetype/src/main/resources/archetype-resources/src/test/java/carina/demo/CucumberWebSampleTest.java
> Fixing cucumber web test in archetype module

- archetype/src/main/resources/archetype-resources/src/test/java/carina/demo/WebMultipleBrowserTest.java
- archetype/src/main/resources/archetype-resources/src/test/resources/testng_suites/web-multiple-browser.xml
> Added web multiple browser test to carina archetype

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> #1148: restored one more workaround use-case for corrupted searchContext

- carina-appcenter/src/main/java/com/qaprosoft/appcenter/AppCenterManager.java
- carina-aws-s3/src/main/java/com/qaprosoft/amazon/AmazonS3Manager.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/skip/ExpectedSkipManager.java
- carina-webdriver/pom.xml
> Refactoring from Reliability section. Issues: L61, L151, L50, L457, L669, L989, L990, L40

- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
> add more logging on info layner about proxy mob killing

- archetype/src/main/resources/archetype-resources/pom.xml
> Changed java version to 11 in carina/archetype

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/TestPhase.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> Before suite

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/DriverFactory.java
> build-snapshot: Made sdf an local variable

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> build-snapshot: Removing useless checking

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/extractor/impl/DivisionElementExtractor.java
> build-snapshot: Casted one of the operands of this division operation to float.

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/IDriverCommandListener.java
> build-snapshot: Using the equals method if value comparison was intended

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
> build-snapshot: Removing the boxing to double in carina-webdriver module

- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/rewrite/CustomRqFilter.java
- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/rewrite/CustomRsFilter.java
> build-snapshot: Init result of replaceAll method in carina-proxy module

- carina-core/src/main/resources/config.properties
- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
- carina-proxy/src/test/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- docs/configuration.md
- docs/proxy.md
> browsermob_ports_range documentation; browsermob_host usage was re-factored

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/LocalizedAnnotations.java
resolves #1222 
Fixes L10N usage for next By types:
- IosClassChain
- IosNsPredicate
- Text
> Support of L10N was fixed for ExtendedFindBy annotation

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Messager.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
> fluent waiters for openUrl

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Messager.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> improvements to the low level actions and loggers

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
> added html report to base directory

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
> fixed desired browser launch

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/L10Nparser.java
Minor update and comments improvement in L10Nparser
Add more comments in L10Nparser usage description.
> Minor update and comments improvement in L10Nparser

- carina-reporting/src/test/java/com/qaprosoft/carina/core/foundation/reporting/EmailTest.java
> Added email unit tests for emailable reporting

- mkdocs.yml
> rearranged order in advanced

- docs/cucumber.md
> minor cucumber docs fix

- docs/advanced/localization.md
- mkdocs.yml
> added localization documentation

- docs/automation/web.md
> Documented pageOpenStrategy

- docs/automation/web.md
> Documented element loading strategy

- carina-utils/src/test/java/com/qaprosoft/carina/core/utils/ConfigurationTest.java
> Added AfterClass to ConfigurationTest

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/common/CommonUtils.java
> build-snapshot: Re-interrupt after catching InterruptedException in carina-utils module

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/L10N.java
- carina-utils/src/test/resources/config.properties
- docs/configuration.md
> Remove enable_l10n config parameter

- carina-utils/src/test/java/com/qaprosoft/carina/core/utils/ConfigurationTest.java
> Default browser name recovery in @AfterClass of ConfigurationTest

- docs/automation/windows.md
- mkdocs.yml
> Docs: added WindowsDriver documentation

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/mobile/MobileCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/windows/WindowsCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/WindowsFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/DevicePoolTest.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/DesktopCapabilitiesTest.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/MobileCapabilitiesTest.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/tvos/AppleTVTest.java
- carina-webdriver/src/test/resources/config.properties
> carina-webdriver: desktop, mobile capabilities unit tests

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
> reorganize AbstractCapabilities.java platformName and browserVersion

- carina-api/pom.xml
- carina-api/src/main/java/com/qaprosoft/apitools/validation/XmlComparator.java
- carina-api/src/main/java/com/qaprosoft/apitools/validation/XmlCompareMode.java
- carina-api/src/main/java/com/qaprosoft/apitools/validation/XmlValidator.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodV2.java
- carina-api/src/test/java/com/qaprosoft/apitools/validation/XmlValidatorTest.java
- carina-api/src/test/resources/validation/xml_file/actual.xml
- carina-api/src/test/resources/validation/xml_file/actual1.xml
- carina-api/src/test/resources/validation/xml_file/actual_error.xml
- carina-api/src/test/resources/validation/xml_file/actual_order.xml
- carina-api/src/test/resources/validation/xml_file/error_message/error.xml
- carina-api/src/test/resources/validation/xml_file/error_message/error_extensible.xml
- carina-api/src/test/resources/validation/xml_file/expected.xml
- carina-api/src/test/resources/validation/xml_file/expected_extensible.xml
Xml validator for api module, which have 2 ways for comparison: strict and non-strict comparison, depending on whether order matters for us
Fixes #801
> added xml validation in api module

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/DevicePoolTest.java
> Remove adb unit tests

- docs/advanced/database.md
- docs/advanced/dataprovider.md
- docs/automation/api.md
- docs/automation/mobile.md
- docs/automation/web.md
- docs/automation/windows.md
- docs/execution.md
- docs/project_structure.md
> Rewrite docs AbstractTest class to IAbstractTest interface

- archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetype/src/main/resources/archetype-resources/src/main/resources/_config.properties
- archetype/src/test/resources/projects/basic/archetype.properties
- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/WindowsFactory.java
- carina-webdriver/src/test/resources/config.properties
- docs/automation/mobile.md
- docs/automation/windows.md
- docs/configuration.md
> added new selenium_url parameter

- carina-azure/src/test/java/com/qaprosoft/azure/AzureClientTest.java
> added expectedExceptions rule in azure negative unit test

- carina-core/src/main/resources/config.properties
> small params fix

- carina-api/src/main/java/com/qaprosoft/apitools/validation/XmlComparator.java
- carina-api/src/main/java/com/qaprosoft/apitools/validation/XmlValidator.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/log/CarinaBodyPrinter.java
- carina-api/src/test/java/com/qaprosoft/apitools/validation/mock/method/MockServer.java
- carina-appcenter/src/main/java/com/qaprosoft/appcenter/AppCenterManager.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/FilterTestsListener.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/skip/ExpectedSkipManager.java
- carina-dataprovider/src/main/java/com/qaprosoft/carina/core/foundation/dataprovider/annotations/XlsDataSourceParameters.java
- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/rewrite/CustomRqFilter.java
- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/rewrite/CustomRsFilter.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/FileManager.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/marshaller/Marshaller.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/L10N.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidService.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/extractor/impl/DivisionElementExtractor.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/internal/AbstractUIObjectListHandler.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/mobile/devices/android/phone/pages/settings/DateTimeSettingsPage.java
> fixed javadoc warnings and errors

- docs/automation/mobile.md
> documented mobile context change

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidService.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
> #1369 deleted screenshot for JavascriptException error for android

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
> added capabilities process

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
> Revert "added capabilities process"

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
> #1392: introduce new chrome_closure boolean field

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringAppiumCommandExecutor.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/IDriverCommandListener.java
- pom.xml
> #1398: hotfixes to mobile utils

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
> added check for ADB Change Language apk path

- carina-api/src/main/java/com/qaprosoft/apitools/builder/BooleanProcessor.java
- carina-api/src/main/java/com/qaprosoft/apitools/builder/NotStringValuesProcessor.java
- carina-api/src/main/java/com/qaprosoft/apitools/builder/PropertiesProcessorMain.java
> build-snapshot: Fix for boolean properties processing in api tests

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/qtest/IQTestManager.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/testrail/ITestRailManager.java
> added labels attach to zebrunner sessions

- archetype/src/main/resources/archetype-resources/pom.xml
> excluded Junit

- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/testrail/ITestRailManager.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/testrail/TestRailCases.java
- carina-reporting/src/test/java/com/qaprosoft/carina/core/foundation/reporting/TestRailTest.java
> #1430: added extra suiteId filder for TestRailCases annotation

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/WindowsFactory.java
> added idleTimeout param, adding values to props as integer if possible

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/L10N.java
- docs/advanced/localization.md
> fixed setLocale method

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> Revert "fixed context and by element searching"

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/AbstractFactory.java
> timeout fix

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/internal/AbstractUIObjectListHandler.java
> #1458: commented waitUntil in AbstractUIObjectListHandler for invoke

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
> Revert "moved openURL from IAndroidUtils to DriverHelper"

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
> added int capabilities parser

- carina-appcenter/src/main/java/com/qaprosoft/appcenter/AppCenterManager.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/skip/ExpectedSkipManager.java
- carina-crypto/src/main/java/com/qaprosoft/carina/core/foundation/crypto/CryptoTool.java
- carina-dataprovider/src/main/java/com/qaprosoft/carina/core/foundation/dataprovider/parser/XLSParser.java
- carina-jenkins/src/main/java/com/qaprosoft/carina/core/foundation/jenkins/JenkinsClient.java
- carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/qtest/IQTestManager.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/testrail/ITestRailManager.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/FileManager.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/XmlFormatter.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/ZipManager.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/DeviceTimeZone.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/marshaller/Marshaller.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/L10N.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/resources/Resources.java
- carina-utils/src/test/java/com/qaprosoft/carina/core/utils/FileManagerTest.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/AndroidService.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/DriverFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedFieldDecorator.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringAppiumCommandExecutor.java
> simplified loggers with exception messaging

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/filter/IFilter.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/filter/impl/OwnerFilter.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/filter/impl/PriorityFilter.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/filter/impl/TagFilter.java
> fixed filters

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
> deleted synchronized for getBaseDir

- carina-utils/src/test/java/com/qaprosoft/carina/core/foundation/exception/ExceptionsTest.java
> imports cleanup

- pom.xml
> #1507: restored jacoco plugin

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
> organized extra call for any WebDriverException in findElements

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
> #1514: handled NPE when starting single test via cmd

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
Simplified html report generation method.
> refactor generateHtmlReport

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- pom.xml
> 1.6.5.248-SNAPSHOT testng pluggable version

- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
- docs/configuration.md
> introduced global disable cache lookup property

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
> #1527: added zebrunnerTestSessionId internal key for driver sessions

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
> handled 4 boolean fields correctly

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedFieldDecorator.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/annotations/DisableCacheLookup.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/CarinaCommandExecutor.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java
- docs/configuration.md
removed non critical workarounds for elements manipulation
> handler of the `driver connection refused` under the huge load

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-reporting/src/main/java/com/qaprosoft/carina/core/foundation/report/testrail/ITestRailManager.java
- carina-reporting/src/test/java/com/qaprosoft/carina/core/foundation/reporting/TestRailTest.java
> Deleted testrail deprecated vars

- archetype/src/main/resources/archetype-resources/pom.xml
- pom.xml
> #1453: switched to zebrunner nexus for snapshot repositories

- carina-api/pom.xml
- carina-api/src/main/java/com/qaprosoft/apitools/validation/JsonCompareKeywords.java
- carina-api/src/main/java/com/qaprosoft/apitools/validation/JsonKeywordsComparator.java
- carina-api/src/main/java/com/qaprosoft/apitools/validation/OgnlKeywordsComparator.java
Ognl json comparator was added
> Ognl validation

- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethod.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodV2.java
- carina-api/src/test/java/com/qaprosoft/apitools/validation/DiffContentTypesValidatorTest.java
- carina-api/src/test/java/com/qaprosoft/apitools/validation/mock/method/DeleteUserMethod.java
- carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodTest.java
- carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/http/HttpMethodTypeTest.java
- carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/http/HttpResponseStatusTypeTest.java
- carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/log/CarinaAPILoggerTest.java
- carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/log/LoggingOutputStreamTest.java
- carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/ssl/PutDocTest.java
- carina-api/src/test/java/com/qaprosoft/mock/apimethod/AutoReplaceUrlPartsMethod.java
- carina-api/src/test/java/com/qaprosoft/mock/apimethod/NoContentTypeMethod.java
- carina-api/src/test/java/com/qaprosoft/mock/apimethod/NoPlaceholdersInURLMethod.java
- carina-api/src/test/java/com/qaprosoft/mock/apimethod/PutDocMethod.java
- carina-api/src/test/java/com/qaprosoft/mock/apimethod/XmlContentTypeMethod.java
- carina-api/src/test/java/com/qaprosoft/mock/server/MockServer.java
- carina-api/src/test/resources/api.properties
- docs/automation/api.md
Automatically to replace url placeholders for api methods.
Re-factoring and re-organization of unit tests
Resolves #1599
> [api] auto replacements of url parts

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/factory/ICustomTypePageFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
> #1575: reuse better getDevice method in ICustomTypePageFactory

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
> #1575: casting driver before looking for device

- carina-api/src/main/java/com/qaprosoft/apitools/validation/JsonKeywordsComparator.java
- carina-api/src/main/java/com/qaprosoft/apitools/validation/JsonValidator.java
- carina-api/src/main/java/com/qaprosoft/apitools/validation/OgnlKeywordsComparator.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodV2.java
- carina-api/src/test/java/com/qaprosoft/apitools/validation/JsonValidatorTest.java
- docs/automation/api.md
Full json dom access via #root keyword was added
> Current value access via #val keyword was added

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringAppiumCommandExecutor.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringSeleniumCommandExecutor.java
> #1654: removed retries in web and mobile commands executors

- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/HTMLUnitCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/OperaCapabilities.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/DesktopFactory.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
- carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/DesktopCapabilitiesTest.java
- pom.xml
> Bump selenium from 4.1 to 4.1.4

- pom.xml
> #1623: bump up to testng 7.6.0

- pom.xml
> Revert "#1623: bump up to testng 7.6.0"

- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/EventFiringSeleniumCommandExecutor.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/screenshot/AutoScreenshotRule.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/screenshot/DebugLevelScreenshotRule.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/screenshot/IScreenshotRule.java
- docs/configuration.md
> #1693: be able to allow/prohibit fullsize screenshoting

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/DriverHelper.java
- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> #1717: reused smart retry interval in DriverHelper waiters

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/report/email/EmailReportGenerator.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/TestResultType.java
> #1733: removed SKIP_ALL and SKIP_ALL_ALREADY_PASSED custom types

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
- carina-core/src/main/resources/config.properties
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
> #1730: removed deprecated health_check_methods and health_check_class

- carina-crypto/src/main/java/com/qaprosoft/carina/core/foundation/crypto/CryptoTool.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
- docs/advanced/security.md
> Revert "Revised security doc and marked methods that use crypto.key as deprec…"

- carina-core/src/main/resources/config.properties
> Revert "Added default value for crypto_key_value"

- archetype/src/main/resources/archetype-resources/pom.xml
- carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
- carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/listeners/TestNamingService.java
> Refactored TUID getting without ds_custom_provider parameter

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
> Optimized capabilities initialization

- docs/advanced/dataprovider.md
> Updated doc about adding TUID using java data provider

- archetype/src/main/resources/archetype-resources/pom.xml
- archetype/src/main/resources/archetype-resources/src/main/java/carina/demo/utils/MobileContextUtils.java
Refactor ProxySampleTest to use BrowserUp proxy instead of BrowserMob proxy
Refactor MobileContextUtils to use correct driver casting
> Bump up carina-core to 8.0.0 and agent to 1.8.0 in archetype

- carina-api/src/test/resources/_config.properties
- carina-api/src/test/resources/crypto.key
- carina-crypto/src/main/java/com/qaprosoft/carina/core/foundation/crypto/CryptoTool.java
> Revert "thrown runtime error if can't load secret key/get cipher instance "

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
>  isVisible method use searchContext

- carina-crypto/pom.xml
- carina-utils/pom.xml
- pom.xml
Also remove relocation pom for the carina-proxy
> add relocation pom for carina-crypto and carina-utils

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
> change default condition waiters to correctly wait presence of elements

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
> replacing agent env param with config env

- docs/advanced/mobile.md
- docs/automation/mobile.md
> Updated links that redirected to a page not found

- docs/advanced/proxy.md
> numeration fix

- archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
> included generation of xml files from archetype into src/main/resources

- docs/advanced/proxy.md
> Paragraphs format inside numeration fix

- docs/advanced/proxy.md
> fix(proxy.md): enclosed the comment by a tab

- docs/advanced/proxy.md
> fix(proxy.md): simplified try/catch code block

- docs/advanced/proxy.md
> fix(proxy.md): redid tabulation

- docs/advanced/proxy.md
> fix(proxy.md): tabulation correction

- docs/advanced/proxy.md
> fix(proxy.md): deleted several paragraphs in sub block of numeration

- carina-webdriver/src/main/java/com/zebrunner/carina/utils/mobile/IMobileUtils.java
> added new dragAndDrop method signature

- carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java
> Using CapabilityHelper for getting platformVersion capability

- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethod.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/annotation/HideResponseHeadersInLogs.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/log/CarinaResponseHeadersLoggingFilter.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/AnnotationContextResolver.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/ContextResolver.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/ContextResolverChain.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/MethodBasedContextResolver.java
- carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/PropertiesContextResolver.java
- docs/automation/api.md
- pom.xml
- HideResponseHeadersInLogs restassured filter was added
- Restassured dependency was upgraded to 5.3.0
> HideResponseHeadersInLogs restassured filter was added

- carina-dataprovider/pom.xml
- pom.xml
> feature: add carina-dataprovider relocation pom

- carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
```
/*    -DBUILD_USER_ID="develop"
1. read from system properties BUILD_USER_ID
2. if it is not empty -> register as owner label for run/launch
3. if it is empty? read env var USERNAME
4. if not empty -> register as owner
Label.attachToTestRun("Author", "Deve Loper");
*/
String owner = System.getProperty("BUILD_USER_ID");
if(owner==null){
owner=System.getenv("USERNAME");
System.out.println( owner);
}
if(owner!=null){
Label.attachToTestRun("Owner", owner);
}
```
> register owner launch attribute

- docs/advanced/dataprovider.md
> updated misprints in dataprovider.md

- src/main/java/com/zebrunner/carina/core/listeners/CarinaListener.java
Changes:
1. decrypt token only
2 . reused agent classes for getting token value
3. added support for specifying an encrypted token in the yaml configuration of the agent
> remove usage of R.AGENT

- src/main/java/com/zebrunner/carina/core/listeners/CarinaListener.java
- src/main/resources/log4j2.xml
> disable netty logs for the DEBUG logger mode

- src/main/java/com/zebrunner/carina/core/listeners/CarinaListener.java
> fix: register config env as agent env

- pom.xml
- src/main/java/com/zebrunner/carina/core/listeners/CarinaListener.java
- src/main/java/com/zebrunner/carina/core/report/testrail/ITestCases.java
> language_tag

- src/main/java/com/zebrunner/carina/core/IAbstractTest.java
- src/main/java/com/zebrunner/carina/core/config/TestConfiguration.java
- src/main/java/com/zebrunner/carina/core/filter/v1/Filter.java
- src/main/java/com/zebrunner/carina/core/filter/v1/IFilter.java
- src/main/java/com/zebrunner/carina/core/filter/v1/IncorrectFilterException.java
- src/main/java/com/zebrunner/carina/core/filter/v1/impl/OwnerFilter.java
- src/main/java/com/zebrunner/carina/core/filter/v1/impl/PriorityFilter.java
- src/main/java/com/zebrunner/carina/core/filter/v1/impl/TagFilter.java
- src/main/java/com/zebrunner/carina/core/filter/v1/rule/Rule.java
- src/main/java/com/zebrunner/carina/core/filter/v2/CountryFilter.java
- src/main/java/com/zebrunner/carina/core/filter/v2/ITestFilter.java
- src/main/java/com/zebrunner/carina/core/filter/v2/MethodsFilter.java
- src/main/java/com/zebrunner/carina/core/filter/v2/TestRunFilterListener.java
- src/main/java/com/zebrunner/carina/core/listeners/FilterTestsListener.java
> feature: tests filter
