zebrunner/carina

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/factory/CustomTypePageFactory.java

First change prevents the LOGGER.debug from just returning just (java.lang.Class) all the time, and returns the actual class name.
The second change looks like the expected/actual would always be the same as it was doing the check after it did an equals on it, so moved it up a level so we can see when differences do occur.

Updating loggers in CustomTypePageFactory to make it easier to debug when theres a problem

---

carina-core/src/main/resources/config.properties
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
pom.xml

Updates related to video recording for iOS. VideoType enum has been removed. For now we should you string parameter.
Added string parameter to config.properties, updated MobileFactory class.

build-snapshot: Updated appium java client to 7.0.0 version

---

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/internal/LocatingElementListHandler.java

- getDefaultCondition() in ExtendedWebElement reverted to previous version to fix https://github.com/qaprosoft/carina/issues/636
- findExtendedWebElement() in ExtendedWebElement was fixed to use cachedElement with valid search context instead of finding root element every time what breaks search context for list of elements
- ^ same for findExtendedWebElements()

build-snapshot: temp fix for abstract ui objects

---

carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethod.java
carina-core/src/main/resources/config.properties
carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
carina-utils/src/test/resources/config.properties

Have a global configuration to skip SSL validation. this is done to skip PKIX issues when running the test suite.
Added a configuration which will be checked when calling an API to ignore SSL validation. 
Added a configuration which will be checked when calling an API to ignore SSL validation. by default, it is set to 'false'. When running tests on a URL with a self-signed https certificate this will be useful to ignore SSL validation.

Have a global configuration to skip SSL validation. this is done to skip PKIX issues

---

carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java

In case of retry_count > 0 the first attempt is marked as skipped. So, we need to quit drivers for this case as well.

build-snapshot: added quit drivers for Skip tests

---

carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java

The logic for reporting has been updated to set "suite_name - test_name" format for test data folder.

build-snapshot: updated logic for report generation

---

carina-hockeyapp/src/main/java/com/qaprosoft/hockeyapp/HockeyAppManager.java

Summary:
It was found that the local check being completed was reversed and never passing, so we've corrected it.  There was also a tweak put in to hand a null exception if the download directory is a new directory with no files in it.

build-snapshot: Tweak to fix checking for local builds and to handle a null exception on an empty directory

---

carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java

Fixed the issue when we are trying to append logs in non-existing file. Changed logic to set `testDirectory.set(newTestDir)` firstly and then perform `LOGGER.debug('message')`

build-snapshot: Fixed logs issue in debug mode for ThreadLogAppender.append(ThreadLogAppender.java:56)

---

carina-aws-s3/pom.xml
pom.xml

1. Download only aws-java-sdk-s3
2. Exclude aws-java-sdk from zafira-client
3. aws-java-sdk-kms and jmespath-java are excluded

improved amazon aws-java-sdk dependencies, download only aws-java-sdk-s3

---

carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
carina-proxy/src/test/java/com/qaprosoft/carina/browsermobproxy/BrowserMobPortsRangeTest.java
carina-proxy/src/test/java/com/qaprosoft/carina/browsermobproxy/BrowserMobTest.java
carina-proxy/src/test/java/com/qaprosoft/carina/proxy/SystemProxyTest.java
carina-proxy/src/test/resources/config.properties
carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/MobileFactory.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/device/Device.java

Related issue: https://github.com/qaprosoft/carina/issues/794
We need this functionality to enable tests with proxy execution in multi-threaded mode. When entire infrastructure is distributed between several selenium boxes
to enable the feature next properties should be set:
-- not to use predefined single port
browsermob_port=NULL
-- range of ports that could be used instead
browsermob_ports_range=55881:55884
Firstly logic checks whether browsermob_port is specified. If true than it will be used for proxy settings. Otherwise it checks whether ports range is predefined.
Then ports are taken from the range one by one for each new test thread

build-snapshot: issues_794: browsermob_ports_range feature was introduced

---

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/android/IAndroidUtils.java

Adding a method to allow users to return the value of installed package versionName. This is essentially a short-form version number of the app's package typically shown within the app itself which can be used for UI validation and passing as needed.
Ex. An installed package's versionCode returns 11200050. The package's versionName returns 11.2.0
This example of the differences is supplied in the method's associated comment.

build-snapshot: Add method to return versionName from system dump

---

carina-api/src/test/java/com/qaprosoft/apitools/validation/JsonSchemaValidatorTest.java
carina-api/src/test/java/com/qaprosoft/apitools/validation/JsonValidatorTest.java

Usage of IOUtils.toString() method was updated in order to fix compilation error in api module test sub-project

compilation error fix in api module

---

pom.xml

Changed line 122 of pom.xml
Trying to build and compile carina it fails due to access denied to:
http://repo.spring.io/plugins-release/. Changed to https

build-snapshot: Changed url protocol htpp to https for spring dependency

---

docs/getting_started.md

a fix for eclipse workspace property name.
with just -Dworkspace I got the following error:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:configure-workspace (default-cli) on project carina: The parameters 'workspace' for goal org.apache.maven.plugins:maven-eclipse-p
> lugin:2.10:configure-workspace are missing or invalid -> [Help 1]
the correct name of this property is `eclipse.workspace`

fix eclipse workspace property name

---

carina-appcenter/src/main/java/com/qaprosoft/appcenter/AppCenterManager.java

The main change here is flipping the order that is scanned through in AppCenter, the flip of the order is done by the updated_at field allowing us to start with the most recently updated app and then work our way backwards.

build-snapshot: Tweak here is flipping the search order to the most recently updated app in AppCenter

---

carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/R.java

updated getProperties logic because 'getProperties' method isn't get CurrentTestOnly properties when trying to create new driver

update getProperties logic in R enum

---

carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/AbstractTestListener.java
carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Messager.java
pom.xml

965 description:
That will remove redundant test results in final testNG report.
Logic should work similarly with ALREADY_PASSED skipped tests processing.
Related to zafira-client PR: qaprosoft/zafira-client#20

Resolves #965 handling of ALREADY_FAILED_BY_KNOWN_BUG SkipExceptions

---

carina-core/src/main/java/com/qaprosoft/carina/core/foundation/AbstractTest.java
pom.xml

build-snapshot: Zebrunner listener was added instead of ZafiraListener

---

carina-utils/src/main/resources/log4j.properties

#988: added default log4j apenders for build process

---

.sonarqube

Since qps-infra(zebrunner starter) 5.0+ this file should be included in order to execute onPush onPullRequest jobs for the jenkins pipeline.
The file describes the configuration for the SonarQube scanner analysis.

Create sonarqube properties file

---

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/ChromeCapabilities.java

When using Chrome 78 and above and adding BMP with MITM into the mix it is seen that an insecure warning message appears by default.  By adding in this capability it will allow us to see if it resolves that message in this snapshot.

build-snapshot: Adding in ACCEPT_INSECURE_CERTS for Chrome Capabilities

---

carina-commons/src/main/java/com/qaprosoft/carina/core/foundation/commons/SpecialKeywords.java
carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
carina-core/src/main/resources/config.properties
carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/windows/WindowsCapabilies.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/DriverFactory.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/factory/impl/WindowsFactory.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/PageOpeningStrategy.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/AbstractPage.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/gui/AbstractUIObject.java
docs/configuration.md

- added support of WinAppDriver usage; capabilities.platformName=Windows should be set for that
- PageOpeningStrategy was introduced. It allows to determine page loading state by marker element visibility; url equality; url + element
- FORCIBLY_DISABLE_DRIVER_QUIT flag was introduced. it allows to disable driver quit at all stages of test execution process. In some cases that's needed for testing of Windows applications

build-snapshot: WinAppDriver support; PageOpeningStrategy was introduced

---

carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/report/ReportContext.java

In some cases tests are getting skipped because of exception in screenshots link getting method.
To prevent that I added exception handling + logging of caught exception message
Example:
`[2020-07-24T09:21:46.990Z] 2020-07-24 09:21:46 Messager [TestNG-tests-8-37] [INFO]  TEST [Gift card test - testValidateGiftCardPlaceholder] PASSED at [09:21:46 2020-07-24]
[2020-07-24T09:21:46.990Z] 2020-07-24 09:21:46 Screenshot [TestNG-tests-8-37] [INFO] Default carina screenshot capturing rules are disabled!
[2020-07-24T09:21:46.990Z] 2020-07-24 09:21:46 Messager [TestNG-tests-8-37] [ERROR]  TEST [Gift card test - testValidateGiftCardPlaceholder] FAILED at [09:21:46 2020-07-24] - Parameter 'directory' is not a directory: /opt/jenkins/workspace/underarmour/phoenix-auto-qa/PHOENIX-PROD-WEB-Acceptance-Chr …

build-snapshot: Exception handling in getting of screenshots link for the report

---

carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/video/VideoAnalyzer.java
carina-utils/src/test/java/com/qaprosoft/carina/core/foundation/utils/video/VideoAnalyzerTest.java

The `VideoAnalyzer`'s `uploadVideo` property is initialized in `AbstractTestListener`, when start/stop test, and retrieved in `IDriverPool`, when someone calls `quitDriver`.
There are cases when we call `quitDriver`, without invoking `AbstractTestListener`, e.g. using Carina from `main` class, without any testing framework. In such a case, `NullPointerException` will arise because `uploadVideo` has not been set beforehand.
Initialize `uploadVideo` with default value to `false`.

Using default value for VideoAnalyzer isEnabled

---

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/listener/DriverListener.java

build-snapshot: Using Arrays.toString() instead of toString()

---

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/Screenshot.java
carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/ScreenshotTest.java

Appium 1.18.3 is output some error messages that `Screenshot` cannot detect to skip screenshoting. This causes stackoverflow.
```
Session ID: 7ec50037-37b7-41a6-a6f2-57c56ecfc425
at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158 …
```

Add more conditions to skip taking screenshots

---

archetype/src/main/resources/META-INF/archetype-post-generate.groovy
archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
archetype/src/test/resources/projects/basic/archetype.properties

Implemented option for not adding demo sources on archetype
Use -Ddemo=false when calling mvn archetype:generate for not adding demo files
resolve #1204

Implemented option for not adding demo sources on archetype

---

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java

Changes in AbstractCapabilities method addChromeOptions
In addChromeOptions, move the chromePrefs HashMap out of the if for AUTO_DOWNLOAD and add a boolean to denote whether we are adding any prefs.
In the if for browserLang, add the intl.accept_languages to the hashmap and set the boolean true
In the if for AUTO_DOWNLOAD, set the boolean true and move the adding of prefs to options out of this if.
Add an if our new boolean is true, then add prefs to the options.
Is there a way I can make this fix back on 6.5.46???

build-snapshot:1225 changes for chrome adding pref for intl.accept_languages

---

carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/exception/NotImplementedException.java
carina-utils/src/test/java/com/qaprosoft/carina/core/foundation/exception/ExceptionsTest.java

https://github.com/qaprosoft/carina/issues/1240
Exception can be thrown when some method is not implemented for the platform.

new exception for issue 1240

---

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/impl/desktop/FirefoxCapabilities.java

Temporarily adding enabling DRM by default to the Firefox Capabilities to see something.

build-snapshot: Adding enabling DRM in the default Firefox capabilities

---

carina-core/src/main/java/com/qaprosoft/carina/core/foundation/IAbstractTest.java
carina-core/src/main/resources/META-INF/services/org.testng.ITestNGListener

As of now, agent's DataProviderInterceptor is completely ignored, so the data provider information is missing. The proposed config resurrects the DataProviderInterceptor as a TestNG listener

Add agent's DataProviderInterceptor to the list of TestNG services

---

archetype/src/main/resources/archetype-resources/src/test/java/carina/demo/ProxySampleTest.java
carina-core/src/main/resources/config.properties
carina-proxy/pom.xml
carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/ProxyPool.java
carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/rewrite/CustomRqFilter.java
carina-proxy/src/main/java/com/qaprosoft/carina/browsermobproxy/rewrite/CustomRsFilter.java
carina-proxy/src/test/java/com/qaprosoft/carina/browsermobproxy/BrowserUpPortsRangeTest.java
carina-proxy/src/test/java/com/qaprosoft/carina/browsermobproxy/BrowserUpTest.java
carina-proxy/src/test/java/com/qaprosoft/carina/proxy/SystemProxyTest.java
carina-proxy/src/test/resources/config.properties
carina-utils/src/main/java/com/qaprosoft/carina/core/foundation/utils/Configuration.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java
carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/core/capability/AbstractCapabilities.java
carina-webdriver/src/test/resources/config.properties
docs/advanced/proxy.md
docs/configuration.md

This Pull Request swaps out the prior BrowserMobProxy library that we were utilizing and moves over to BrowserUpProxy which can be called the successor to BrowserMobProxy, as the former hasn't been updated in a few years.
There may be 1-2 more commits to this after snapshot testing has concluded.

build-snapshot: Moving from BrowserMobProxy to BrowserUpProxy

---

carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethod.java
carina-api/src/test/java/com/qaprosoft/apitools/validation/mock/method/DeleteUserMethod.java
carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodTest.java
carina-api/src/test/resources/api.properties

Fixed "Incorrect url for API call which is hard coded in api.properties #1564" ticket's bug.
Found bug in the init method of AbstractApiMethod class. After not correct splitting methodPath field got incorrect url. Changed splitting logic (103 line). Created unit-test for the method in AbstractApiMethodTest class. Added url-query to api.properties file.

fixed bug of splitting for methodPath url inside init method

---

carina-appcenter/src/main/java/com/qaprosoft/appcenter/AppCenterManager.java

Adding **scope=tester** to queryparam due to observed developer builds not intended for public use being made available in AppCenter. These builds have a unique package name which differs from test parameters and is causing failure to launch problems.

build-snapshot: Adding new queryparam value scope=tester in AppcenterManager

---

carina-aws-s3/src/main/java/com/qaprosoft/amazon/AmazonS3Manager.java

Hotfix for AmazonS3Manager. 
Currently, it is impossible to get objects from S3 if there are more than 1000 objects.

Hotfix for AmazonS3Manager

---

pom.xml

excluded out-of-dated netty-tcnative-boringssl-static from azure module

---

carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java
carina-core/src/main/resources/log4j2.xml

If we initialize logger in onStart in CarinaListener, all classes that we already accessed will have INFO log level, so we lost debug logs

init logger in constructor

---

carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethod.java
carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodV2.java
carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/http/HttpResponseStatus.java
carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/http/HttpResponseStatusType.java
carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/AnnotationContextResolver.java
carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/ContextResolver.java
carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/ContextResolverChain.java
carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/MethodBasedContextResolver.java
carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/resolver/PropertiesContextResolver.java
carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/http/HttpResponseStatusTest.java
carina-api/src/test/java/com/qaprosoft/carina/core/foundation/api/http/HttpResponseStatusTypeTest.java
pom.xml

Updating the SuccessfulHttpStatus annotation to have an optional message override.
Solution for [issue-1910](https://github.com/zebrunner/carina/issues/1910). This updates the `@SuccessfulHttpStatus` annotation to allow an optional message override instead of using the hard coded statusLine value from the `HttpResponseStatusType` enum. If no override is given then the default message from the enum object will be used. This also updates the annotation converters and assertions to use the new `HttpResponseStatus` object built from the annotation and enum.

[issue-1910] build-snapshot : updating the SuccessfulHttpStatus annotation to allow a message override 

---

carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElement.java
carina-webdriver/src/test/java/com/qaprosoft/carina/core/foundation/webdriver/decorator/ExtendedWebElementTest.java
pom.xml

The isElementPresent method can throw a StaleElementReferenceException in a couple of scenarios. These are if the object has a non-null `element` field that is stale or if the search context is a web element (e.g. it represents a nested element search) and the search context is stale.
This change wraps the execution of the wait to catch any StaleElementReferenceException and returns false in the case that one is caught. It also adds some unit tests for both true and false cases with mocking.

[Issue-2035] build-snapshot : ExtendedWebElement#isElementPresent should not throw StaleElementReferenceException
